# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando_nombre', models.CharField(max_length=50)),
                ('comando_descripcion', models.CharField(max_length=150)),
                ('comando_sintaxis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='diccionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diccionario_nombre', models.CharField(max_length=50)),
                ('diccionario_descripcion', models.CharField(max_length=100)),
                ('diccionario_logo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ejemplo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejemplo_entrada', models.CharField(max_length=50)),
                ('ejemplo_salida', models.CharField(max_length=50)),
                ('ejemplo_explicacion', models.CharField(max_length=150)),
                ('comando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diccionarios.comando')),
            ],
        ),
        migrations.CreateModel(
            name='opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_nombre', models.CharField(max_length=50)),
                ('opcion_descripcion', models.CharField(max_length=150)),
                ('comando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diccionarios.comando')),
            ],
        ),
        migrations.AddField(
            model_name='comando',
            name='diccionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diccionarios.diccionario'),
        ),
    ]
