# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diccionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comando',
            old_name='comando_descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='comando',
            old_name='comando_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='comando',
            old_name='comando_sintaxis',
            new_name='sintaxis',
        ),
        migrations.RenameField(
            model_name='diccionario',
            old_name='diccionario_descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='diccionario',
            old_name='diccionario_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='diccionario',
            old_name='diccionario_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='ejemplo',
            old_name='ejemplo_entrada',
            new_name='entrada',
        ),
        migrations.RenameField(
            model_name='ejemplo',
            old_name='ejemplo_explicacion',
            new_name='explicacion',
        ),
        migrations.RenameField(
            model_name='ejemplo',
            old_name='ejemplo_salida',
            new_name='salida',
        ),
        migrations.RenameField(
            model_name='opcion',
            old_name='opcion_descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='opcion',
            old_name='opcion_nombre',
            new_name='nombre',
        ),
    ]
