# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionarios', '0003_auto_20161027_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comando',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diccionario',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ejemplo',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
