# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionarios', '0004_auto_20161126_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplo',
            name='salida',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
