use linuxtricks;

delete from programas_atajo where id > 0;
delete from programas_programa where id > 0;
delete from programas_categoria where id > 0;
delete from diccionarios_ejemplo where id > 0;
delete from diccionarios_opcion where id > 0;
delete from diccionarios_comando where id > 0;
delete from diccionarios_diccionario where id > 0;

ALTER TABLE programas_atajo AUTO_INCREMENT = 1;
ALTER TABLE programas_programa AUTO_INCREMENT = 1;
ALTER TABLE programas_categoria AUTO_INCREMENT = 1;
ALTER TABLE diccionarios_ejemplo AUTO_INCREMENT = 1;
ALTER TABLE diccionarios_opcion AUTO_INCREMENT = 1;
ALTER TABLE diccionarios_comando AUTO_INCREMENT = 1;
ALTER TABLE diccionarios_diccionario AUTO_INCREMENT = 1;

insert into diccionarios_diccionario (nombre,descripcion,logo) values ('Linux (general)','comandos básicos','linux.svg');
insert into diccionarios_diccionario (nombre,descripcion,logo) values ('Ubuntu','sistema operativo','ubuntu.svg');
insert into diccionarios_diccionario (nombre,descripcion,logo) values ('Bash','scripts','terminal.svg');
insert into diccionarios_diccionario (nombre,descripcion,logo) values ('VI','editor de texto avanzado','vim.svg');

insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ac','Imprime estadísticas acerca del tiempo que han estado conectado los usuarios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('adduser','Ver useradd.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('alias','Crea atajos de comandos, lista los alias actuales.','alias[opciones][nombreAlias[=Cadena]]',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('apt-get','Herramienta de actualización/instalación remota de paquetes en sistemas basados en debian.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('arp','Permite obtener/manipular la lista de direcciones MAC/Ip que el sistema ve.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('arping','Envía ARP REQUEST a otros equipos en la red.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('arptables','Firewall similar en funciones a iptables pero para control de tráfico de protocolo arp.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('at','Programa trabajos, comandos, scripts para su ejecución posterior.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('atq','Lista los trabajos programados pendientes de ejecutar por el comando at.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('awk','Análisis y procesamiento de patrones en archivos y listados.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('basename','Permite eliminar la ruta del nombre de un archivo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('bc','Calculadora y lenguaje matemático, muy potente.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('biosdecode','Información sobre el BIOS.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('blkid','Muestra atributos de dispositivos de bloque (discos, usb, etc.) tales como LABEL y UUID, entre otros.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('bzcat','Descomprime archivos comprimidos o empaquetados mediante bzip2.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('bzip2','Compresor / descompresor de archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('bzmore','Permite ver el contenido de archivos comprimidos o empaquetados mediante bzip2.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('cal','Despliega un calendario.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('cat','Muestra el contenido de archivos y concatena archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('cd','Cambiar de directorio.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('cfdisk','Herramienta de particionamiento de discos, usada en sistemas debian principalmente.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('chage','Permite cambiar la información (expiración, caducidad, etc) de la contraseña de un usuario.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('chattr','Cambia atributos extendidos de archivos y directorios','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('chfn','Cambia la información usada en finger.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('chgrp','Cambia el grupo de un archivo(s) o carpetas(s).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('chkconfig','Controla/consulta el modo en que los servicios se ejecutan o no al inicio del sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('chmod','Cambia los permisos de un archivo(s) o carpetas(s).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('chown','Cambia el propietario de un archivo(s) o carpetas(s).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('chpasswd','Actualiza passwords o contraseñas en modo batch. Puede actualizar contraseñas de grupos de usuarios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('chroot','Ejecuta comandos de root en un shell restringido a un directorio y sus subdirectorios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('chsh','Cambia tu shell por defecto o shell de login.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('cleanlinks','Limpia enlaces simbólicos que no tengan relación y también remueve directorios vacios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('clear','Limpia la terminal.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('cmp','Compara dos archivos byte por byte.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('convertquota','Convierte de los viejos formatos quota.user y quota.group a los nuevos formatos de aquota.user y aquota.group.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('cpio','Copia, crea, comprime y extrae archivos en distintos formatos y entre equipos o localmente.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('crontab','Administra archivos cron para los usuarios y root.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('curl','Permite descargar o transferir urls.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('cut','Remueve secciones (columnas principalmente) de cada línea de un archivo o archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('date','Muestra/establece la fecha y hora actual.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('dc','Calculadora interactiva.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('dd','Convierte y copia archivos y sistemas de archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ddate','Muestra la fecha en formato del calendario Discordante.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('df','Muestra el uso de espacio de discos duros o particiones.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('diff','Busca y muestra diferencias entre archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('dig','Utilería para consultas a servidores DNS.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('dircolors','Configuración de colores para el comando ls.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('dirs','Permite mostrar, manipular la lista de directorios utilizados en la pila. (ver popd y pushd)','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('dmesg','Muestra los mensajes del arranque del sistema (boot).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('dmidecode','Lista hardware del equipo directamente del BIOS. (también: lshw)','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('dos2unix','Convierte archivos de formato MS-DOS a formato Unix/Linux.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('du','Muestra el uso de espacio de archivos y directorios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('dump','Permite la creación de respaldos para los sistemas de archivos ext2 y ext3.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('echo','Imprime una línea de texto, variables, o contenido a un archivo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('edquota','Administra el control de cuotas de disco de usuario y grupos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('egrep','Es igual que el comando grep -E, para uso de expresiones regulares.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('eject','Desmonta y expulsa un medio removible, como cdroms.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('env','Ejecuta un programa en un entorno modificado.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ethtool','Permite desplegar o cambiar valores de una tarjeta de red.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('exit','Sale del shell o terminal actual.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('expect','Permite crear secuencias de diálogos y programar sesiones interactivas con otros comandos o scripts.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('export','Exporta el valor de una variable.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('exportfs','Mantiene una lista de sistemas de archivos del tipo NFS que han sido exportados.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('expr','Evaluador de expresiones matemáticas.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('factor','Encuentra los números primos de un número dado.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('fc','Lista, edita y reejecuta comandos previamente ejecutados.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('fdisk','Herramienta para particionar discos, común a casi todas las distros.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('fgrep','Es igual que grep -F para uso de expresiones regulares en búsquedas de archivos y listados.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('file','Determina el tipo de archivo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('find','Búsqueda de archivos, multitud de opciones de búsqueda.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('findfs','Busca un sistema de archivos por UUID o LABEL (etiqueta).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('findsmb','Lista información sobre equipos que respondan a paquetes SMB. Lista una red Windows. (Parte del paquete Samba)','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('finger','Muestra información sobre los usuarios del sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('fortune','Imprime un adagio al azar.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('fping','Permite mandar paquetes ICMP (pings) a múltiples equipos en una red y determinar si están vivos o no.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('free','Muestra el espacio usado y libre de memoria RAM y Swap.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('fsck','Herramienta para verificar/reparar sistemas de archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('fuser','Identifica procesos utilizando archivos o conexiones (sockets).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('gawk','Análisis y procesamiento de patrones en archivos y listados. (versión gnu)','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('gcc','Compilador de C y de C++ de GNU.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('gedit','Editor de textos de gnome.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('gpasswd','Permite la administración del archivo /etc/group','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('gpg','Herramienta de encriptación y de generación de certificados de seguridad (opengpg).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('grep','Busca patrones de cadenas dentro de archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('groupadd','Crea un nuevo grupo en el sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('groupdel','Elimina un grupo en el sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('groupmod','Modifica un grupo en el sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('groups','Imprime los grupos a los que pertenece un usuario.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('gzip','Comprime/expande archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('halt','Apaga el equipo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('hdparm','Establece y muestra características sobre los discos duros.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('head','Despliega las primera líneas de un archivo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('help','Ayuda sobre los comandos internos de bash.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('history','Muestra el historial de comandos del usuario.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('host','Utileria de consulta a sevidores DNS.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('hostname','Despliega el nombre del equipo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('htpasswd','Administra archivos de usuario/contraseña para autentificación básica de Apache.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('hwclock','Muestra/Establece la fecha/hora del bios o hardware. (Fecha/Hora del sistema con date)','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('id','Muestra el UID (User ID) y GID (Group ID) del usuario','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ifconfig','Muestra/Configura las interfaces de red del sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ifstat','Pequeña utileria que permite observar estadísticas de las interfaces de red en tiempo real.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('init','Control de inicialización de un nivel de ejecucción.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('insmod','Inserta módulos en el kernel.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ipcalc','Realiza cálculos simples sobre direcciones IP.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ipcount','Identificación de rangos de red, cálculo de IPs.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('iptab','Muestra una tabla de direcciones IP de acuerdo al prefijo CIDR','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('iptables','Herramienta de configuración del firewall de Linux.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('iptraf','Analizador de tráfico de red en modo de texto.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('iwconfig','Configura una tarjeta de red inalámbrica.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('iwlist','Obtiene información detallada de una tarjeta inalámbrica.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('jobs','Muestra los trabajos del usuario en suspensión o en background.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('kate','Editor de textos de KDE.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('kill','Termina procesos, mas correctamente envía señales a procesos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('killall','Termina procesos del mismo nombre o conjunto.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('last','Muestra información de los últimos usuarios logueados.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('lastb','Muestra información de los últimos intentos fallidos de loguearse.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('less','Muestra el contenido de un archivo, permite búsquedas y movimento hacía atrás y adelante.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ln','Crea enlaces (accesos directos) suaves y duros de archivos y directorios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('locale','Información específica sobre las variables de entorno locales.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('locate','Indexa y busca archivos. Mas seguro utilizar slocate.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('losetup','Define y controla dispositivos del tipo loop.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('lpq','Muestra los documentos para imprimir en la cola de impresión.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('lpr','Añade un documento a la cola de impresión.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ls','Lista archivos y directorios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('lshw','Lista hardware del equipo directamente del BIOS. (también: dmidecode)','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('lsmod','Muestra el estatus de los módulos en el kernel.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('lsof','Muestra archivos abiertos de un programa en ejecucción, o de un usuario, proceso, etc.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('lspci','Lista los dispositivos pci del sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('lsusb','Lista los dispositivos usb del sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('mail','Envía y recibe correos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('man','Muestra el manual del comando indicado.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('mc','Manejador de archvivos con soporte de mouse en modo de texto, no todas las distro lo tienen.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('mcedit','Editor de textos de mc.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('md5sum','Comprueba (y genera) archivos con firma de certificación md5.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('mkdir','Crea directorios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('mkfs','Construye un sistema de archivos de Linux.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('mkpasswd','Generador de contraseñas. (Paquete del programa expect).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('modinfo','Muestra información acerca de los módulos del kernel.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('modprobe','Herramienta que añade/remueve módulos del kernel.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('more','Paginador similar a less pero menos funcioanal, ya que sale avanza y no retocede.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('mount','Monta dispositvos de almacenamiento en particiones indicadas.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('mtools','Conjunto de utilidades para acceder a discos DOS desde Linux.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('mv','Mueve archivos y directorios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('netstat','Herramienta de red que muestra conexiones, tablas de ruteo, estadísticas de interfaces, etc.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('nice','Ejecuta un programa con una prioridad de ejecución distinta a la normal.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('nohup','Ejecuta un programa inmune a los hangups y sin salida a una terminal.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('openssl','Control, administración, generación de certificados de seguridad.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('partprobe','Indica al sistema operativo de los cambios indicados en /etc/fstab','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('passwd','Cambia la contraseña del usuario indicado.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ping','Manda un echo_request (solicitud de eco) a un equipo en al red.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('pkill','Manda señales a procesos basado en sus atributos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('popd','Remueve entradas (directorios utilizados) de la lista de directorios utilizados en la pila. (ver dirs y pushd)','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('pr','Formatea o convierte archivos de texto para imprimirlos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ps','Muestra los procesos del sistema o del usuario o ambos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('pstree','Muestra los procesos en forma de árbol.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('pushd','Agrega entradas (directorios utilizados) en la lista de directorios (pila o stack). (ver dirs y popd)','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('pwck','Verifica la integridad del archivo /etc/passwd','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('pwconv','Agrega o establece la protección shadow el archivo /etc/passwd.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('quota','Permite ver el uso de cuotas por usuario.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('quotacheck','Crea, verifica, administra sistemas de cuotas de disco','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('quotaoff','Desactiva el control de cuotas de discos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('quotaon','Activa el control de cuotas de discos para usuarios y grupos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('rdesktop','Abre terminales gráficas hacia equipos Windows.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('reboot','Reinicia el equipo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('renice','Cambia la prioridad de un proceso o programa en ejecución.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('repquota','Reporte de uso de cuotas de disco.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('resolveip','Resuelve la ip del dominio o host que se indique.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('rev','Invierte las líneas de un archivo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('rm','Borra o elimina archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('route','Muestra/altera la tabla de ruteo IP.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('rpm','Programa para la instalación/actualización/eliminación de paquetes, distros basadas en redhat.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('runlevel','Muestra el nivel de ejecución actual y anterior del sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('scp','Copia archivos entre equipos, parte del paquete openssh (protocolo de comunicación encriptado).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('screen','Administrador de terminales virtuales.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('sed','Editor en línea que filtra y transforma archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('service','Ejecuta/detiene servicios en modo manual.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('set','Muestra o establece el entorno de variables para el usuario actual.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('sha1sum','Comprueba (y genera) archivos con firma de certificación sha1.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('shopt','Habilita o deshabilita variables opcionales del comportamiento del shell.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('shred','Elimina archivos de manera segura e irrecuperable.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('shutdown','Apaga o reinicia el equipo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('sort','Ordena líneas de archivos y listas','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ss','Utileria similar a netstat pero más básica, listados rápidos de sockets establecidos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('ssh','Programa de login remoto seguro, programa del paquete openssh (protocolo de comunicación encriptado).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('startx','Inicia una sesión X.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('su','Cambia del usuario actual al indicado.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('sudo','Permite indicar que usuario ejecuta que comandos de root.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('sync','Forza bloques en memoria a discos, actualiza el superbloque.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('tac','Igual que cat, muestra y/o concatena archivos pero al revés.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('tail','Muestra la parte final de un archivo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('tailf','Sinónimo del comando tail -f, permite ver en tiempo real la parte final de un archivo, es decir, conforme se va escribiendo. Util para monitorear bitácoras.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('tar','Herramienta empaquetadora/compresora de archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('testparm','Revisa archivos smb.conf de samba por errores o correciones.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('time','Devuelve el tiempo en que se ejecutó el comando o programa indicado.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('top','Muestra los procesos del sistema de manera interactiva y continua.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('touch','Crea archivos vacios, cambia fechas de acceso y/o modificación de archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('tput','Cambia valores o capacidades de la terminal, en base a terminfo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('traceroute','Imprime la ruta de los paquetes de red hasta el destino indicado.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('tty','Imprime el nombre de la terminal en la que se esta.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('tzselect','Permite establecer una zona o huso horario.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('umask','Establece una máscara de permisos para cuando se crean directorios y archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('umount','Desmonta sistemas de archivos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('unalias','Elimina alias de comandos, creados con el comando alias.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('uname','Despliega información del sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('uniq','Omite o reporta sobre líneas repetidas en un archivo o listado.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('units','Convertidor de unidades de un sistema a otro, soporta decenas de sistemas de medición.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('up2date','Herramienta de actualización/instalación remota de paquetes, (usada en redhat, centos).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('uptime','Muestra que tanto tiempo lleva prendido el equipo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('urpme','Programa del paquete urpmi para desinstalar o eliminar paquetes.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('urpmi','Herramienta de actualización/instalación remota de paquetes, distros basadas en rpm (usada en mandriva).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('useradd','Añade usuarios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('userdel','Elimina usuarios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('usermod','Modifica información de usuarios.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('users','Muestra los nombres de usuario de todos los usuarios conectados actualmente al sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('vi','Editor visual de pantalla, editor de textos, que encuentras en todas las distros Linux.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('vim','Igual que el vi pero mejorado.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('visudo','Editor para el archivo de configuración /etc/sudoers de sudo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('vmstat','Proporciona información sobre la memoria virtual.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('w','Muestra quien esta conectado al sistema y que esta haciendo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('wall','Manda un mensaje a todas las terminales.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('warnquota','Configura /etc/warnquota.conf como complemento de mensajes para cuotas de disco.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('wc','Cuenta palabras, líneas, caracteres de un archivo o listado.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('wget','Descargador de archivos desde Internet, no interactivo.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('whatis','Descripción corta, en una línea de un comando o programa.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('whereis','Localiza el binario, fuentes y/o librerias, y documentación de un comado.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('which','Muestra la ruta completa de un comando.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('who','Muestra quien esta conectado al sistema.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('whoami','Muestra el usuario actual.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('xhost','Control de acceso para sesiones X.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('xkill','Mata o termina a un cliente X, es decir, a un programa gráfico.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('yes','Imprime una cadena repetidamente hasta que sea terminado o matado el comando.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('yum','Herramienta de actualización/instalación remota de paquetes, distros basadas en rpm (usada en fedora, redhat y derivados).','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('zcat','Descomprime / muestra archivos comprimidos con gunzip (es idéntico a utilizar gunzip -c)','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('zenity','Despliega varios tipos de diálogos en X desde una terminal.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('zless','Permite mostrar el contenido de archivos comprimidos.','',1);
insert into diccionarios_comando (nombre,descripcion,sintaxis,diccionario_id) values ('zmore','Permite mostrar el contenido de archivos comprimidos.','',1);

insert into diccionarios_ejemplo (entrada,salida,descripcion,comando_id) values ('alias lhost=\'cd /var/www/html\'',NULL,'este comando configura a lhosts como la orden \'cd /var/www/html\'',3);

insert into diccionarios_opcion (nombre,descripcion,comando_id) values ('-a','Elimina todas las definiciones de alias del programa de ejecución de shell actual',3);
insert into diccionarios_opcion (nombre,descripcion,comando_id) values ('-p','imprime la lista de alias en formato \'nombre=valor\'',3);


insert into programas_programa (nombre,descripcion,logo) values ('GIMP','editor de imágenes','gimp.svg');
insert into programas_programa (nombre,descripcion,logo) values ('LibreOffice','suite de ofimática','libreoffice.svg');
insert into programas_programa (nombre,descripcion,logo) values ('Blender','modelado y edición de gráficos 3d','blender.svg');
insert into programas_programa (nombre,descripcion,logo) values ('Audacity','editor de audio','audacity.svg');

insert into programas_categoria (nombre) values('archivo');
insert into programas_categoria (nombre) values('ver');
insert into programas_categoria (nombre) values('herramientas');
insert into programas_categoria (nombre) values('ayuda');
insert into programas_categoria (nombre) values('editar');
insert into programas_categoria (nombre) values('capas');
insert into programas_categoria (nombre) values('selecciones');
insert into programas_categoria (nombre) values('plug-ins');
insert into programas_categoria (nombre) values('diálogos');

insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Selección en rectángulo','R ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Selección en elipse','E ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Selección libre','F ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Varita mágica','U ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Selección por color','Shift+O ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Tijeras','I ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Rutas','B ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Cuentagotas (selector de color)','O ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Mover','M ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Cortar y redimensionar','Shift+C ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Rotar','Shift+R ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Escalar','Shift+T ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Inclinar','Shift+S ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Perspectiva','Shift+P ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Voltear','Shift+F ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Texto','T ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Cubo de relleno','Shift+B ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Mezclar','L ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Lápiz','N ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Pincel','P ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Goma de borrar','Shift+E ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Aerógrafo','A ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Tinta','K ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Clonar','C ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Enfoque/Desenfoque','Shift+U',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Emborronar','S ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Iluminar/Oscurecer','Shift+D ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Cambiar color frente/fondo','X ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Colores por defecto','D ',3,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Nueva imagen','Ctrl+N ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen','Ctrl+O ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen como nueva capa','Ctrl+Alt+O ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Duplicar imagen','Ctrl+D ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen reciente 1','Ctrl+1 ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen reciente 2','Ctrl+2 ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen reciente 3','Ctrl+3 ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen reciente 4','Ctrl+4 ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen reciente 5','Ctrl+5 ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen reciente 6','Ctrl+6 ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen reciente 7','Ctrl+7 ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen reciente 8','Ctrl+8 ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen reciente 9','Ctrl+9 ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir imagen reciente 10','Ctrl+0 ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Guardar imagen','Ctrl+S ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Guardar como','Shift+Ctrl+S ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Salir','Ctrl+Q ',1,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Menú principal','F10',2,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Menú desplegable','Shift+F10',2,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Pantalla completa','F11',2,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Máscara rápida','Shift+Q ',2,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Cerrar ventana documento','Ctrl+W ',2,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Zoom +','Ctrl+Rueda de ratón',2,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Zoom –','Ctrl+Rueda de ratón',2,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Zoom 1:1','1',2,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Capas','Ctrl+L ',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Pinceles','Shift+Ctrl+B ',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Patrones','Shift+Ctrl+P ',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Gradientes','Ctrl+G ',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Opciones de herramientas','Shift+Ctrl+T ',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Paletas','Ctrl+P ',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Información de ventana','Shift+Ctrl+I ',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Ventana de navegación','Shift+Ctrl+N ',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Cerrar ventana','Alt+F4',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Saltar al siguiente control','Tab',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Salar al control anterior','Shift+Tab',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Introducir un nuevo valor','Enter',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Activar botón o control actual','Space',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Cambiar pestañas','Ctrl+Alt+PgUp',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Abrir localización','Shift+L ',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Subir carpeta','Alt+ up',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Bajar carpeta','Alt+ down',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Carpeta home','Alt+Home',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Cerrar diálogo','Esc',9,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Deshacer','Ctrl+Z ',5,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Rehacer','Ctrl+Y ',5,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Copiar selección','Ctrl+C ',5,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Cotar selección','Ctrl+X ',5,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Copiar visible','Ctrl+Shift+C ',5,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Pegar como capa nueva','Ctrl+Shift+V ',5,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Pegar al portapapeles','Ctrl+V ',5,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Limpiar selección','Ctrl+K ',5,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Seleccionar capa por encima','PgUp',6,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Seleccionar capa por debajo','PgDn',6,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Seleccionar primera capa','Home',6,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Seleccionar ultima capa','End',6,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Combinar capas visibles','Ctrl+M ',6,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Aplanar capas','Ctrl+H ',6,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Alternar selecciones','Ctrl+T ',7,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Seleccionar todo','Ctrl+A ',7,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Deseleccionar','Shift+Ctrl+A ',7,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Invertir selección','Ctrl+I ',7,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Selección flotante','Shift+Ctrl+L ',7,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('A partir de una ruta','Shift+V ',7,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Repetir el último filtro','Ctrl+F ',8,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Mostrar el último filtro','Shift+Ctrl+F',8,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Ayuda','F1',4,1);
insert into programas_atajo(descripcion,combinacion,categoria_id,programa_id) values ('Ayuda contextual','Shift+F1',4,1);
