# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atajo',
            old_name='atajo_combinacion',
            new_name='combinacion',
        ),
        migrations.RenameField(
            model_name='atajo',
            old_name='atajo_descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='programa_descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='programa_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='programa_nombre',
            new_name='nombre',
        ),
    ]
