# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_auto_20161027_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria_nombre',
            new_name='nombre',
        ),
    ]
