# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0003_auto_20161027_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atajo',
            name='combinacion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='programa',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
